# -*- coding: utf-8 -*-
"""Copy of Python _beginer level

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IDhEectRZOVFoMCiPzdoPf8G1QBnf0y4

**Day-1**(Basic code)
"""

print(3 + 2)

print(3 - 2)

print(3 * 2)

print(3 / 2)

print(3 ** 2)

print(3 % 2)

print(3 // 2)

"""**Checking Data Types**"""

print(type(10))

print(type(3.14))

print(type(1+3j))

print(type('Asabeneh'))

print(type([1, 2, 3]))

print(type({'name': 'Asabeneh'}))

print(type({9.8, 3.14, 2.7}))

print(type((9.8, 3.14, 2.7)))

print(type(3 == 3))

print(type(3 >= 3))

print(3 > 2)

print(3 >= 2)

print(3 < 2)

print(2 < 3)

print (3 ==2)

print(3 !=2)

print(len('mango') == len('avocado'))

print(len('mango') != len('avocado'))

print(len('mango') < len('avocado'))

print(len('milk') != len('meat'))

print(3 > 2 and 4 > 3)

print(3 > 2 and 4 < 3)

print(3 < 2 and 4 < 3)

a = 10
a

a, b, c = 10, 20, 30
a
b
c

print(a)
print(b)
print(c)
10
20
30

print(a, b, c)

1nit = 67

_nit = 78
_nit

IF = 89
IF

i = 4
i

f = 110.78
print(f)
print(type(f))

f1 = 3e0
f1

f2 = 3e1
f2

f3 = 3e2
f3

f4 = 2.3e3
f4

True + False

True + True

True + False * True - False

True + (False * True) - False

True + (False * True) - True

num1 = 20
num2 = 30
add= num1+num2
add

num1=20
num2=30
add=num1+num2
print('The addition of', num1, 'and', num2, 'is=', add)

c= 10 + 20j
c

type(c)

d= 30 + 40j
print(c)
print(d)

c + d

a = '5,5'
type(a)

c- d

a

c

a = 5
b = 6
c = a+b
print(c)

int(2.3) #float to int

int(True) #bool to int

complex(10.2 , 23)

complex(10.2, 23.34567)

complex(True, False)

complex(False, True)

str(10)

str(101.10)

bool(10)

bool(0)